[package]
name = "tcp_connection"
edition = "2024"
version.workspace = true

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
