[package]
name = "just_enough_vcs"
edition = "2024"
license-file = "LICENSE-MIT"
authors = ["Weicao-CatilGrass (GitHub)"]

[features]
all = ["utils", "lib"]
utils = [
    "cfg_file",
    "data_struct",
    "hex_display",
    "sha1_hash",
    "tcp_connection",
]
cfg_file = []
data_struct = []
hex_display = []
sha1_hash = []
tcp_connection = []
lib = []
deprecated = []

[workspace]
members = [
    "docs",
    "ffi",
    "systems/_asset",
    "systems/_asset/macros",
    "systems/_asset/test",
    "systems/_config",
    "systems/_constants",
    "systems/_constants/macros",
    "systems/_framework",
    "systems/_framework/space_macro",
    "systems/sheet",
    "systems/sheet/macros",
    "systems/vault",
    "systems/workspace",
    "utils/data_struct",
    "utils/hex_display",
    "utils/sha1_hash",
    "utils/tcp_connection",
    "utils/tcp_connection/tcp_connection_test",

    # LEGACY AREA
    "legacy_actions",
    "legacy_data",
    "legacy_data/tests",
    "legacy_systems/action",
    "legacy_systems/action/action_macros",
    "legacy_utils/cfg_file",
    "legacy_utils/cfg_file/cfg_file_derive",
    "legacy_utils/cfg_file/cfg_file_test",
    # LEGACY AREA
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
# Macro & code gen
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
toml = "0.9"

# Text processing
just_fmt = "0.1.2"
regex = "1.12"

# Async runtime
tokio = { version = "1.50", features = ["full"] }

# Error handling
thiserror = "2"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
codegen-units = 16
incremental = true
lto = false
panic = "unwind"

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "off"
codegen-units = 1
incremental = false
lto = "fat"
panic = "abort"
strip = "symbols"

[build-dependencies]
chrono = "0.4"
toml = "0.9"

[dev-dependencies]
tokio = { version = "1.48", features = ["rt"] }
criterion = "0.8"

[[bench]]
name = "sheet_benchmark"
harness = false

[[bench]]
name = "sheet_tree_benchmark"
harness = false

[dependencies]
# ffi
jvlib = { path = "ffi" }

# Documents
vcs_docs = { path = "docs" }

# Utils
cfg_file = { path = "legacy_utils/cfg_file" }
data_struct = { path = "utils/data_struct" }
hex_display = { path = "utils/hex_display" }
sha1_hash = { path = "utils/sha1_hash" }
tcp_connection = { path = "utils/tcp_connection" }

# Systems
asset_system = { path = "systems/_asset" }
config_system = { path = "systems/_config" }
constants = { path = "systems/_constants" }
framework = { path = "systems/_framework" }
sheet_system = { path = "systems/sheet" }
vault_system = { path = "systems/vault" }
workspace_system = { path = "systems/workspace" }

# Legacy
vcs_data = { path = "legacy_data" }
vcs_actions = { path = "legacy_actions" }
action_system = { path = "legacy_systems/action" }
