[package]
name = "just_enough_vcs"
edition = "2024"
license-file = "LICENSE-MIT"
authors = ["Weicao-CatilGrass (GitHub)"]

[features]
all = [
    "cfg_file",
    "data_struct",
    "sha1_hash",
    "tcp_connection",
    "string_proc",
    "lib",
]
cfg_file = []
data_struct = []
sha1_hash = []
tcp_connection = []
string_proc = []
lib = []

[workspace]
members = [
    "utils/cfg_file",
    "utils/cfg_file/cfg_file_derive",
    "utils/cfg_file/cfg_file_test",

    "utils/data_struct",

    "utils/sha1_hash",

    "utils/tcp_connection",
    "utils/tcp_connection/tcp_connection_test",

    "utils/string_proc",

    "systems/asset",
    "systems/asset/macros",
    "systems/asset/test",

    "systems/action",
    "systems/action/action_macros",

    "systems/_constants",
    "systems/_constants/macros",

    # LEGACY AREA
    "legacy_data",
    "legacy_data/tests",
    "legacy_actions",
    # LEGACY AREA

    "docs",

    "ffi",
]

[workspace.package]
version = "0.1.0"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
codegen-units = 16
incremental = true
lto = false
panic = "unwind"

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "off"
codegen-units = 1
incremental = false
lto = "fat"
panic = "abort"
strip = "symbols"

[build-dependencies]
chrono = "0.4"
toml = "0.9"

[dependencies]
# Utils
cfg_file = { path = "utils/cfg_file" }
data_struct = { path = "utils/data_struct" }
sha1_hash = { path = "utils/sha1_hash" }
tcp_connection = { path = "utils/tcp_connection" }
string_proc = { path = "utils/string_proc" }

# Systems
asset = { path = "systems/asset" }
action_system = { path = "systems/action" }
constants = { path = "systems/_constants" }

# ffi
jvlib = { path = "ffi" }

# Documents
vcs_docs = { path = "docs" }

# Legacy
vcs_data = { path = "legacy_data" }
vcs_actions = { path = "legacy_actions" }
