[package]
name = "cfg_file_test"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg_file = { path = "../../cfg_file", features = ["default"] }
tokio = { version = "1.46.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }