[package]
name = "sheet_system"
edition = "2024"
version.workspace = true

[dependencies]
hex_display = { path = "../../utils/hex_display" }

asset_system = { path = "../_asset" }
constants = { path = "../_constants" }
sheet_system_macros = { path = "macros" }

serde.workspace = true
tokio.workspace = true
thiserror.workspace = true
just_fmt.workspace = true

memmap2 = "0.9"
sha2 = "0.11"
